# Generated by Django 5.2.3 on 2025-06-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_user_profile_email_profile_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('release_year', models.IntegerField()),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('miniseries', 'MiniSeries'), ('animatedshow', 'Animated Show'), ('comic', 'Cartoon Comic')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_year'],
            },
        ),
    ]
