# Generated by Django 5.2.3 on 2025-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_preference',
            field=models.CharField(choices=[('file', 'Uploaded File'), ('url', 'URL')], default='file', max_length=10),
        ),
    ]
