# Generated by Django 5.2.3 on 2025-06-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_avatar_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_preference',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='reread',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='rewatched',
            field=models.IntegerField(default=0),
        ),
    ]
