# Generated by Django 5.2.3 on 2025-06-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_profile_avatar_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecontent',
            name='alt_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basecontent',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('animatedshow', 'Animated Show'), ('comic', 'Cartoon Comic')], max_length=20),
        ),
        migrations.CreateModel(
            name='ContentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('prequel', 'Prequel'), ('sequel', 'Sequel'), ('adaptation', 'Adaptation'), ('side_story', 'Side Story'), ('parent_story', 'Parent Story')], max_length=20)),
                ('from_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='core.basecontent')),
                ('to_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='core.basecontent')),
            ],
        ),
    ]
