# Generated by Django 5.2.3 on 2025-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_basecontent_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('watching', 'Watching'), ('completed', 'Completed'), ('on_hold', 'On-Hold'), ('dropped', 'Dropped'), ('plan_to_watch', 'Plan to Watch/Read')], default='plan_to_watch', max_length=20),
        ),
    ]
